Inicializacion de Hugo
manusaurio/taller5web pull request #2
Opened 2023-10-30 22:33 UTC by giandominella

Close #1

2023-10-30 23:57 UTC, manusaurio requested changes
Hay algunos nombres incorrectos nomás, pero antes de cambiarlos vas a tener que actualizar tu repo local porque yo force-pusheé contra él. Como caso _excepcional,_ `git pull --rebase` debería reconocer este estado de actualización forzada y rehacerte el historial de commits.

Hacé eso primero, después cambiale los nombres a los archivos (podés usar `git mv` para mandarlo al stash de cambios de una, así no va a ser necesario que hagas `git add`), commiteá (`git commit`) y después pusheá (`git push`).

Ej:

```
$ git mv assets/.gitkeep.txt assets/.gitkeep
$ git mv content/.gitkeep.txt content/.gitkeep
$ git commit -m "Correción de nombres de gitkeep"
```

2023-10-30 23:57 UTC, manusaurio commented on assets/.gitkeep.txt
El archivo este debería llamarse `.gitkeep`, no `gitkeep.txt`

2023-10-30 23:57 UTC, manusaurio commented on content/.gitkeep.txt
Este otro archivo también debería llamarse `.gitkeep` y no `gitkeep.txt`

2023-11-03 21:45 UTC, manusaurio approved these changes

2023-11-03 21:46 UTC, manusaurio approved these changes
LGTM

2023-11-03 23:17 UTC, EBonepelche approved these changes
/pedir cambios/aprobar

2023-11-03 23:19 UTC, merged